### PR TITLE
Small change to allow trace spaces on mixedelements

### PR DESCRIPTION
**Pull request by andreavs**
Hi! This is a great piece of software. I am interested in using it for solving the Nernst-Planck equation for a set of ion concentrations with an EMI-like boundary. The equations are coupled and require a MixedElement-approach. This small change allows for a mixed element in my case, and should work identically in the previously implemented cases.

### CODE REVIEW

**Comment by MiroK** [comment]
Thanks for the patch! I forgot about the mixed elements/function spaces 
because with cbc block these would be lists of elements/spaces.

**Comment by MiroK** [comment]
Hi @andreavs, I was doing some cleanup which touched the mixed element [traces](https://github.com/MiroK/fenics_ii/commit/b609cf09b3b35f8c2c1da7e607425fc3a38d6c7d). Does the modification work in your code?

**Comment by andreavs** [comment]
Hi @MiroK! I pulled the most recent commit, and it looks to me like it works. The code runs and produces the same results as it did yesterday.

**Comment by MiroK** [comment]
Perfect, thanks.

**Pull request merged**
